INFO:root:Bot found: ./initialisation.py
INFO:root:Bot found: ./.c9/metadata/workspace/initialisation.py
INFO:root:Bot initialisation playing as titi onto localhost:9876
INFO:root:Waiting for engagement...
INFO:root:Waiting for init new game...
INFO:root:New game cea25389-d873-4cbd-b5a0-320f22593e36


INIT :::


INITcea25389-d873-4cbd-b5a0-320f22593e36TO2[0];1;7CELLS:0(0,0)'100'30'8'I,1(0,5)'100'30'8'I,2(5,0)'100'30'8'I,3(5,5)'200'30'8'II,4(5,10)'100'30'8'I,5(10,5)'100'30'8'I,6(10,10)'100'30'8'I;6LINES:0@4800OF1,0@4800OF2,2@4700OF3,3@4700OF4,4@4800OF6,5@4800OF6
Traceback (most recent call last):
  File "./pooobot.py", line 87, in <module>
    main()
  File "./pooobot.py", line 66, in main
    bot.init_pooo(init_string)
  File "/home/elrubio/Documents/mes cours/polytech/semestre 5/projet/LSLW-TeamStars/initialisation.py", line 61, in init_pooo
    carte.dict_distances = carte.graphe_dictionnaire_generator("t_distances")
  File "/home/elrubio/Documents/mes cours/polytech/semestre 5/projet/LSLW-TeamStars/classes.py", line 91, in graphe_dictionnaire_generator
    l_dic_p.append( dict( zip(liste_ide_voisins[i], liste_poids[i]) ) )
TypeError: unhashable type: 'list'
